P133Allup/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P133Allup.DataAccessLayer;
using P133Allup.Models;
using P133Allup.ViewModels.BasketViewModels;

namespace P133Allup.Controllers
{
	public class BasketController : Controller
	{
		private readonly AppDbContext _context;

		public BasketController(AppDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			string basket = HttpContext.Request.Cookies["basket"];
			List<BasketVM> basketVMs = null;
			if (basket != null)
			{
				basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
			}
			else
			{
				basketVMs = new List<BasketVM>();
			}
			foreach (BasketVM basketVM in basketVMs)
			{
				basketVM.Title = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Title;
				basketVM.Image = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).MainImage;
				basketVM.Price = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Price;
			}
			return View(basketVMs);
		}


		public async Task<IActionResult> AddBasket(int? id)
		{
			if (id == null)
			{
				return BadRequest();
			}


			if (!await _context.Products.AnyAsync(p => p.IsDeleted == false && p.Id == id)) { return NotFound(); }

			string basket = HttpContext.Request.Cookies["basket"];

			List<BasketVM> basketVMs = null;


			if (string.IsNullOrWhiteSpace(basket))
			{
				basketVMs = new List<BasketVM>
				{
				   new BasketVM {Id= (int)id,Count=1}
				};

			}
			else
			{
				basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);

				if (basketVMs.Exists(b => b.Id == id))
				{
					basketVMs.Find(b => b.Id == id).Count += 1;
				}
				else
				{
					basketVMs.Add(new BasketVM { Id = (int)id, Count = 1 });
				}
			}


			basket = JsonConvert.SerializeObject(basketVMs);

			HttpContext.Response.Cookies.Append("basket", basket);

			foreach (BasketVM basketVM in basketVMs)
			{
				Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id && p.IsDeleted == false);

				if (product != null)
				{
					basketVM.ExTax = product.ExTax;
					basketVM.Price = product.DiscountedPrice > 0 ? product.DiscountedPrice : product.Price;
					basketVM.Title = product.Title;
					basketVM.Image = product.MainImage;
				}
			}

			return PartialView("_BasketPartial", basketVMs);
		}
		public async Task<IActionResult> GetBasket()
		{
			return Json(JsonConvert.DeserializeObject<List<BasketVM>>(HttpContext.Request.Cookies["basket"]));
		}

		
		public async Task<IActionResult> DeleteBasket(int? id)
		{
			if (id == null) return BadRequest();

			if (!await _context.Products.AnyAsync(p => p.IsDeleted == false && p.Id == id)) return NotFound();

			string basket = HttpContext.Request.Cookies["basket"];

			List<BasketVM> basketVMs = null;

			if (string.IsNullOrWhiteSpace(basket)) { return BadRequest(); }

			else
			{
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
                if (basketVMs.Exists(b=>b.Id == id))
				{
                    BasketVM basketVM = basketVMs.Find(b => b.Id == id);
                    basketVMs.Remove(basketVM);
                    basket = JsonConvert.SerializeObject(basketVMs);
                    HttpContext.Response.Cookies.Append("basket", basket);
                }
				else
				{
					return NotFound();
				}
			}
			foreach (BasketVM basketVM in basketVMs)
			{
				Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVM.Id && p.IsDeleted == false);

				if (product != null)
				{
					basketVM.ExTax = product.ExTax;
					basketVM.Price = product.DiscountedPrice > 0 ? product.DiscountedPrice : product.Price;
					basketVM.Title = product.Title;
					basketVM.Image = product.MainImage;
				}
			}

			return PartialView("_BasketProductTablePartial", basketVMs);
		}

        public async Task<IActionResult> GetBasketForCart()
        {

            string basket = HttpContext.Request.Cookies["basket"];
            List<BasketVM> basketVMs = null;

            if (string.IsNullOrWhiteSpace(basket))
            {
                return BadRequest();
            }
            else
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
            }
            foreach (BasketVM basketVM in basketVMs)
            {
                Product product = await _context.Products
                    .FirstOrDefaultAsync(p => p.Id == basketVM.Id && p.IsDeleted == false);

                if (product != null)
                {
                    basketVM.ExTax = product.ExTax;
                    basketVM.Price = product.DiscountedPrice > 0 ? product.DiscountedPrice : product.Price;
                    basketVM.Title = product.Title;
                    basketVM.Image = product.MainImage;
                }
            }
            return PartialView("_BasketPartial", basketVMs);
        }
    }
}

P133Allup/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P133Allup.DataAccessLayer;
using P133Allup.Models;
using P133Allup.ViewModels;
using P133Allup.ViewModels.BasketViewModels;
using P133Allup.ViewModels.ProductViewModels;

namespace P133Allup.Controllers
{
    public class ProductController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly AppDbContext _context;

        public ProductController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index(int pageIndex = 1)
        {
            IQueryable<Product> products = _context.Products.Where(p=>p.IsDeleted==false);

            return View(PageNatedList<Product>.Create(products,pageIndex,10));
        }

        [HttpGet]

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Product product = await _context.Products
                .Include(p => p.ProductImages.Where(p => p.IsDeleted == false))
                .Include(p=>p.Brand)
                .Include(p=>p.ProductTags.Where(pt=>pt.IsDeleted == false)).ThenInclude(pt=>pt.Tag)
                .Include(p=>p.Reviews.Where(p=>p.IsDeleted == false))
                .FirstOrDefaultAsync(p=>p.IsDeleted == false && p.Id == id);

            if (product== null)
            {
                return NotFound();
            }
            ProductReviewVM productReviewVM = new ProductReviewVM
            {
                Product = product,
                Review = new Review {ProductId=id},
            };

            return View(productReviewVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Member")]

        public async Task<IActionResult> AddReview(Review review)
        {
            Product product = await _context.Products
               .Include(p => p.ProductImages.Where(p => p.IsDeleted == false))
               .Include(p => p.Brand)
               .Include(p => p.ProductTags.Where(pt => pt.IsDeleted == false)).ThenInclude(pt => pt.Tag)
               .Include(p => p.Reviews.Where(p => p.IsDeleted == false))
               .FirstOrDefaultAsync(p => p.IsDeleted == false && p.Id == review.ProductId);

            ProductReviewVM productReviewVM = new ProductReviewVM { Product = product, Review = review };

            if (!ModelState.IsValid) return View("Detail", productReviewVM);

            AppUser appUser = await _userManager.FindByNameAsync(User.Identity.Name);

            if (product.Reviews != null && product.Reviews.Count() > 0 && product.Reviews.Any(r => r.UserId == appUser.Id))
            {
                ModelState.AddModelError("Name", "Siz artiq fikir bildirmisiniz!");
                return View("Detail", productReviewVM);

            }
            review.CreatedBy = $"{appUser.Name} {appUser.SurName}";
            review.CreatedAt= DateTime.UtcNow.AddHours(4);

            await _context.Reviews.AddAsync(review);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Detail) ,new {id = product.Id});
        }


        public async Task<IActionResult> ProductModal(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            Product product = await _context.Products.Include(x=>x.ProductImages).FirstOrDefaultAsync(x => x.IsDeleted == false && x.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return PartialView("_ModalPartial", product);
}

        public async Task<IActionResult> Search(int? categoryId,string search)
        {

            if (categoryId != null && categoryId > 0)
            {
                if (!await _context.Categories.AnyAsync(c => c.Id == categoryId))
                {
                    return BadRequest();
                }
             
            }
            IEnumerable<Product> products = await _context.Products
                 .Where(p => p.IsDeleted == false && categoryId != null && categoryId > 0 ? p.CategoryId == categoryId : true &&
                 (p.Title.ToLower().Contains(search.ToLower()) || p.Brand.Name.ToLower().Contains(search.ToLower()))).ToListAsync();

            return PartialView("_SearchPartial",products);
        }
        public async Task<IActionResult> ChangeBasketProductCount(int? id, int count)
        {
            if (id == null)
            {
                return BadRequest();
            }
            if (!_context.Products.Any(p => p.Id == id))
            {
                return NotFound();
            }
            string basket = HttpContext.Request.Cookies["basket"];
            List<BasketVM> basketVMs = null;
            if (basket != null)
            {
                basketVMs = JsonConvert.DeserializeObject<List<BasketVM>>(basket);
                basketVMs.Find(p => p.Id == id).Count = count;
                basket = JsonConvert.SerializeObject(basketVMs);
                HttpContext.Response.Cookies.Append("basket", basket);
                foreach (BasketVM basketVM in basketVMs)
                {
                    basketVM.Title = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Title;
                    basketVM.Image = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).MainImage;
                    basketVM.Price = _context.Products.FirstOrDefault(p => p.Id == basketVM.Id).Price;
                }
                return PartialView("_BasketProductTablePartial", basketVMs);
            }
            else
            {
                return BadRequest();
            }
        }

    }
}

P133Allup/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P133Allup.DataAccessLayer;

namespace P133Allup.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(IDictionary<string, string> settings)
        {
            return View(await Task.FromResult(settings));
        }
    }
}

P133Allup/Views/Shared/_AddReviewPartial.cshtml
@model Review

<div class="rating-star d-flex align-items-center">
	<span class="title">Rating:</span>
	<div class="rate">
		<input form="reviewForm" type="radio" id="star5"  asp-for="Start"  value="5" />
		<label for="star5" title="5">5 stars</label>
		<input form="reviewForm" type="radio" id="star4" asp-for="Start" value="4" />
		<label for="star4" title="4">4 stars</label>
		<input form="reviewForm" type="radio" id="star3" asp-for="Start" value="3" />
		<label for="star3" title="3">3 stars</label>
		<input form="reviewForm" type="radio" id="star2" asp-for="Start" value="2" />
		<label for="star2" title="2">2 stars</label>
		<input form="reviewForm" type="radio" id="star1" asp-for="Start" value="1" />
		<label for="star1" title="1">1 star</label>
	</div>
</div>
<form id="reviewForm" method="post" asp-controller="Product" asp-action="AddReview">
	<input type="hidden" name="ProductId" value="@Model.ProductId" />
	<div class="row">
		<div class="col-md-6">
			<div class="single-form">
				<label asp-for="Name"></label>
				<input asp-for="Name" placeholder="Name">
			</div>
		</div>
		<div class="col-md-6">
			<div class="single-form">
				<label asp-for="Email"></label>
				<input asp-for="Email" placeholder="Email">
				<span asp-validation-for="Email" class="text text-danger"></span>
			</div>
		</div>
		<div class="col-md-12">
			<div class="single-form">
				<label asp-for="Description"></label>
				<textarea asp-for="Description" placeholder="Write a review"></textarea>
			</div>
		</div>
		<div class="col-md-12">
			<div class="single-form">
				<button class="main-btn">Add Review</button>
			</div>
		</div>
	</div>
</form>

P133Allup/Views/Shared/_AddressFormPartial.cshtml
@model Address
<form method="post" asp-controller="account" asp-action="AddAddress">
	<div class="row">
		<div class="col-md-12 mt-30">
		<input asp-for="IsMain" id="account">
			<label asp-for="IsMain"></label>
	</div>
	<div class="col-md-6">
		<div class="single-form">
			<input asp-for="Country" placeholder="Country">
		</div>
	</div>
	<div class="col-md-6">
		<div class="single-form">
			<input asp-for="City" placeholder="City">
		</div>
	</div>
	<div class="col-md-12">
		<div class="single-form">
			<input asp-for="State" placeholder="State">
		</div>
	</div>
	<div class="col-md-12">
		<div class="single-form">
			<input asp-for="PostalCode" placeholder="Postal Code">
		</div>
	</div>
	<div class="col-md-12">
		<div class="single-form">
			<input asp-for="AddressLine" placeholder="Address Line">
		</div>
	</div>
	<div class="col-md-6">
		<div class="single-form">
			<button type="submit" class="main-btn main-btn-2">Save Change</button>
		</div>
	</div>
	</div>
</form>

P133Allup/Views/Shared/_BasketPartial.cshtml
@model IEnumerable<BasketVM>

<div class="cart-btn">
    <a asp-controller="Basket">
        <i class="icon ion-bag"></i>
        <span class="text">Cart :</span>
        <span class="total">$@Model.Sum(b=>b.Count * b.Price)</span>
        <span class="count">@Model.Count()</span>
    </a>
</div>
<div class="mini-cart">
    <ul class="cart-items">
        @foreach (BasketVM basketVM in Model)
        {
            <li>
                <div class="single-cart-item d-flex">
                    <div class="cart-item-thumb">
                        <a><img src="~/assets/images/product/@basketVM.Image" alt="product"></a>
                        <span class="product-quantity">@(basketVM.Count)x</span>
                    </div>
                    <div class="cart-item-content media-body">
                        <h5 class="product-name"><a href="single-product.html">@basketVM.Title</a></h5>
                        <span class="product-price">€@basketVM.Price</span>
                        <span class="product-color"><strong>Color:</strong> White</span>
                        <a href="#" class="product-close"><i class="fal fa-times"></i></a>
                    </div>
                </div>
            </li>
        }
    </ul>
    <div class="price_content">
        <div class="cart-subtotals">
            <div class="products price_inline">
                <span class="label">Subtotal</span>
                <span class="value">€@Model.Sum(b=>b.Count *b.Price)</span>
            </div>
            <div class="tax price_inline">
                <span class="label">Taxes</span>
                <span class="value">€@Model.Sum(b=>b.Count *b.ExTax)</span>
            </div>
        </div>
        <div class="cart-total price_inline">
            <span class="label">Total</span>
            <span class="value">€@(Model.Sum(b => b.Count * b.Price) + @Model.Sum(b => b.Count * b.ExTax))</span>
        </div>
    </div> <!-- price content -->
    <div class="checkout text-center">
        <a asp-controller="Basket" asp-action="Index" class="main-btn">Checkout</a>
    </div>
</div> <!-- mini cart -->

P133Allup/Views/Shared/_BasketProductTablePartial.cshtml
@model IEnumerable<BasketVM>

@foreach (BasketVM basketVM in Model)
{
	<tr>
		<td>
			<div class="product-image">
				<img src="assets/images/product/@basketVM.Image" alt="cart">
			</div>
		</td>
		<td>
			<div class="product-title">
				<h4 class="title"><a href="single-product.html">@basketVM.Title</a></h4>
			</div>
		</td>
		<td>
			<div class="product-price">
				<span class="price">€@basketVM.Price</span>
			</div>
		</td>
		<td>
			<div class="product-quantity">
				<div class="quantity mt-15 d-flex">
					<button type="button" class="sub"><i class="fal fa-minus"></i></button>
					<input class="productCount" data-productId="@basketVM.Id" type="text" value="@basketVM.Count" />
					<button type="button"><i class="fal fa-plus"></i></button>
				</div>
			</div>
		</td>
		<td>
			<div class="product-total">
				<span class="total-amount">€@(basketVM.Count * basketVM.Price)</span>
			</div>
		</td>
		<td>
			<div data-productId="@basketVM.Id" class="product-delete">
				<a href="#"><i class="fal fa-trash-alt"></i></a>
			</div>
		</td>
	</tr>
}


<h2 class="cart-total price-inline" style="float:right">Total Price:€@(Model.Sum(b => b.Count * b.Price) + @Model.Sum(b => b.Count * b.ExTax))</h2>

P133Allup/Views/Shared/_Layout.cshtml
@inject ILayoutService layoutservice

@{
    IDictionary<string, string> settings = await layoutservice.GetSettings();
    IEnumerable<Category> categories = await layoutservice.GetCategories();
    IEnumerable<BasketVM> basketVMs = await layoutservice.GetBaskets();

    HeaderVM headerVM = new HeaderVM
            {
                BasketVMs=basketVMs,
                Settings=settings,
                Categories=categories
            };
}


<!doctype html>
<html class="no-js" lang="en">


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:46:32 GMT -->
<head>
    <meta charset="utf-8">

    <!--====== Title ======-->
    <title>Allup - Electronics Responsive eCommerce HTML Template.</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" type="image/png">


    <!-- CSS
    ============================================ -->

    <!--===== Vendor CSS (Bootstrap & Icon Font) =====-->

    <link rel="stylesheet" href="~/assets/css/plugins/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/fontawesome.min.css">

    <!--===== Plugins CSS (All Plugins Files) =====-->

    <link rel="stylesheet" href="~/assets/css/plugins/slick.css">
    <link rel="stylesheet" href="~/assets/css/plugins/animate.css">
    <link rel="stylesheet" href="~/assets/css/plugins/jquery-ui.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/default.css">

    <!--====== Main Style CSS ======-->
    <link rel="stylesheet" href="~/assets/css/style.css">


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->

    <!-- <link rel="stylesheet" href="~/assets/css/vendor/plugins.min.css">
    <link rel="stylesheet" href="~/assets/css/style.min.css"> -->

</head>

<body>

    <!--====== PRELOADER PART START ======-->

    <div id="preloader">
        <div class="preloader">
            <span></span>
            <span></span>
        </div>
    </div>

    <!--====== PRELOADER PART ENDS ======-->

    <!--====== Header Part Start ======-->

     @await Component.InvokeAsync("Header",headerVM)

    <!--====== Header Part Ends ======-->

    @RenderBody()

    <!--====== Brand Part Start ======-->

    <div class="brand-area pt-80">
        <div class="container-fluid custom-container">
            <div class="row brand-active">
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="~/#">
                            <img src="~/assets/images/brand/brand-1.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="~/#">
                            <img src="~/assets/images/brand/brand-2.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="~/#">
                            <img src="~/assets/images/brand/brand-3.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="~/#">
                            <img src="~/assets/images/brand/brand-4.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="~/#">
                            <img src="~/assets/images/brand/brand-5.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="~/#">
                            <img src="~/assets/images/brand/brand-6.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
                <div class="col-lg-2">
                    <div class="single-brand">
                        <a href="~/#">
                            <img src="~/assets/images/brand/brand-4.jpg" alt="brand">
                        </a>
                    </div> <!-- single brand -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </div>

    <!--====== Brand Part Ends ======-->

    <!--====== Features Banner Part Start ======-->

    <section class="features-banner-area pt-80 pb-100">
        <div class="container-fluid custom-container">
            <div class="features-banner-wrapper d-flex flex-wrap">
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon1.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">Free Shipping</h3>
                        <p>Free shipping on all US order</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon2.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">Support 24/7</h3>
                        <p>Contact us 24 hours a day</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon3.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">100% Money Back</h3>
                        <p>You have 30 days to Return</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon4.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">90 Days Return</h3>
                        <p>If goods have problems</p>
                    </div>
                </div> <!-- single features banner -->
                <div class="single-features-banner d-flex">
                    <div class="banner-icon">
                        <img src="~/assets/images/banner-icon/icon5.png" alt="Icon">
                    </div>
                    <div class="banner-content media-body">
                        <h3 class="banner-title">Payment Secure</h3>
                        <p>We ensure secure payment</p>
                    </div>
                </div> <!-- single features banner -->
            </div> <!-- features banner wrapper -->
        </div> <!-- container -->
    </section>

    <!--====== Features Banner Part Ends ======-->

    <!--====== Newsletter Part Start ======-->

    <section class="newsletter-area pt-100 pb-100 bg_cover" style="background-image: url(assets/images/bg-newletter.jpg)">
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-8">
                    <div class="newsletter-content">
                        <h2 class="newsletter-title">Subscribe our newsletter</h2>
                        <p>allup is a powerful eCommerce HTML Template</p>

                        <div class="newsletter-forn">
                            <form action="#">
                                <input type="text" placeholder="Your Email address">
                                <button class="main-btn">Subscribe</button>
                            </form>
                        </div>
                    </div> <!-- newsletter content -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>

    <!--====== Newsletter Part Ends ======-->

    <!--====== Footer Part Start ======-->

    @await Component.InvokeAsync("Footer",settings)

    <!--====== Footer Part Ends ======-->

    <!--====== Quick View Part Start ======-->

    <!-- Modal -->
    <div class="modal fade " id="productQuickModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            </div> <!-- Modal content -->
        </div> <!-- Modal dialog -->
    </div> <!-- Modal -->

    <!--====== Quick View Part Ends ======-->

    <!--====== BACK TOP TOP PART START ======-->

    <a href="~/#" class="back-to-top"><i class="ion-android-arrow-up"></i></a>

    <!--====== BACK TOP TOP PART ENDS ======-->




    <!--====== Vendors js ======-->
    <script src="~/assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/assets/js/vendor/modernizr-3.7.1.min.js"></script>
    @RenderSection("Scripts",false);

    <!--====== Plugins js ======-->
    <script src="~/assets/js/plugins/popper.min.js"></script>
    <script src="~/assets/js/plugins/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/slick.min.js"></script>
    <script src="~/assets/js/plugins/jquery.countdown.min.js"></script>
    <script src="~/assets/js/plugins/jquery-ui.min.js"></script>


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->

    <!-- <script src="~/assets/js/plugins.min.js"></script> -->


    <!--====== Main Activation js ======-->
    <script src="~/assets/js/main.js"></script>
    <script src="~/assets/js/custom.js"></script>




</body>


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:47:16 GMT -->
</html>

P133Allup/Views/Shared/_ProductListPartial.cshtml
@model IEnumerable<Product>


<div class="product-items">
    <div class="row product-active">

        @for (int i = 0; i < (int)Math.Ceiling((decimal)Model.Count() / 2); i++)
        {
            <div class="col-lg-2">
                @foreach (Product product in Model.Skip(i * 2).Take(2))
                {
                    <div class="single-product mt-30">
                        <div class="product-image">
                            <a href="single-product.html">
                                <img class="first-image" src="~/assets/images/product/@product.MainImage" alt="product">
                                <img class="second-image" src="~/assets/images/product/@product.HoverImage" alt="product">
                            </a>
                            <ul class="product-meta">
                                <li><a class="addToBasket" data-id="@product.Id" href="#"><i class="icon ion-bag"></i></a></li>
                                <li><a href="#"><i class="icon ion-android-favorite-outline"></i></a></li>
                                <li><a href="#"><i class="icon ion-android-options"></i></a></li>
                                <li>
                                    <a id="productModal" data-toggle="modal" data-target="#productQuickModal"
                               asp-action="ProductModal" asp-controller="Product" asp-route-id="@product.Id"><i class="icon ion-android-open"></i>  </a>
                                </li>
                            </ul>
                        </div>
                        <div class="product-content">
                            <ul class="product-rating">
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                            </ul>
                            @if (product.DiscountedPrice > 0)
                            {
                                <span class="discount-product">@(((product.Price - product.DiscountedPrice) / product.Price) * 100)%</span>
                            }
                            <h4 class="product-title"><a href="single-product.html">@product.Title</a></h4>
                            <div class="product-price">
                                @if (product.DiscountedPrice > 0)
                                {
                                    <span class="regular-price">€@product.Price</span>
                                    <span class="price-sale">€@product.DiscountedPrice</span>
                                }
                                else
                                {
                                    <span class="price-sale">€@product.Price</span>
                                }

                            </div>
                        </div>
                    </div> <!-- single product -->
                }
            </div>
        }

    </div> <!-- row -->
</div> <!-- product items -->